services:
  package:
    build:
      context: .
      secrets:
        - github_token   # points to a file created by compose from the secret below
    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
    ports:
      - "8001:80"

secrets:
  github_token:
    environment: GITHUB_TOKEN  # compose will read the token value from your env
