services:
  service:
    build:
      context: .
    environment:
      LOGGING_CONFIG_LEVEL: "${LOGGING_CONFIG_LEVEL:-DEBUG}"
      LOGGING_CONFIG_NAMESPACES: '${LOGGING_CONFIG_NAMESPACES:-["", "uvicorn"]}'
      TOKEN_VALIDATOR_TYPE: "${TOKEN_VALIDATOR_TYPE:-}"
      TOKEN_VALIDATOR_OIDC_ISSUER: "${TOKEN_VALIDATOR_OIDC_ISSUER:-}"
      TOKEN_VALIDATOR_OIDC_JWKS_URI: "${TOKEN_VALIDATOR_OIDC_JWKS_URI:-}"
      TOKEN_VALIDATOR_OIDC_AUDIENCE: "${TOKEN_VALIDATOR_OIDC_AUDIENCE:-}"
      TOKEN_VALIDATOR_OIDC_ALGORITHMS: '${TOKEN_VALIDATOR_OIDC_ALGORITHMS:-[]}'
    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
    ports:
      - "8001:80"
